import tkinter as tk


class VentanaOperaciones(tk.Toplevel):
    def __init__(self, parent, estructura_datos):
        super().__init__(parent)
        self.title(f"Operaciones para {estructura_datos}")
        self.geometry("400x200")

        # Crear los botones de operaciones según la estructura de datos
        if estructura_datos == "Pila":
            boton_insertar = tk.Button(self, text="Insertar")
            boton_insertar.pack(side=tk.LEFT, padx=5)
            boton_eliminar = tk.Button(self, text="Eliminar")
            boton_eliminar.pack(side=tk.LEFT, padx=5)
            boton_buscar = tk.Button(self, text="Buscar")
            boton_buscar.pack(side=tk.LEFT, padx=5)
        elif estructura_datos == "Cola":
            boton_insertar = tk.Button(self, text="Insertar")
            boton_insertar.pack(side=tk.LEFT, padx=5)
            boton_eliminar = tk.Button(self, text="Eliminar")
            boton_eliminar.pack(side=tk.LEFT, padx=5)
            boton_buscar = tk.Button(self, text="Buscar")
            boton_buscar.pack(side=tk.LEFT, padx=5)
        elif estructura_datos == "Lista Simple":
            boton_insertar_inicio = tk.Button(self, text="Insertar al Inicio")
            boton_insertar_inicio.pack(side=tk.LEFT, padx=5)
            boton_insertar_final = tk.Button(self, text="Insertar al Final")
            boton_insertar_final.pack(side=tk.LEFT, padx=5)
            boton_eliminar_inicio = tk.Button(self, text="Eliminar del Inicio")
            boton_eliminar_inicio.pack(side=tk.LEFT, padx=5)
            boton_eliminar_final = tk.Button(self, text="Eliminar del Final")
            boton_eliminar_final.pack(side=tk.LEFT, padx=5)
            boton_buscar = tk.Button(self, text="Buscar")
            boton_buscar.pack(side=tk.LEFT, padx=5)
        elif estructura_datos =="Lista Circular":
            boton_insertar_inicio = tk.Button(self, text="Insertar al Inicio")
            boton_insertar_inicio.pack(side=tk.LEFT, padx=5)
            boton_insertar_final = tk.Button(self, text="Insertar al Final")
            boton_insertar_final.pack(side=tk.LEFT, padx=5)
            boton_eliminar_inicio = tk.Button(self, text="Eliminar del Inicio")
            boton_eliminar_inicio.pack(side=tk.LEFT, padx=5)
            boton_eliminar_final = tk.Button(self, text="Eliminar del Final")
            boton_eliminar_final.pack(side=tk.LEFT, padx=5)
            boton_buscar = tk.Button(self, text="Buscar")
            boton_buscar.pack(side=tk.LEFT, padx=5)
            btn_rotar_derecha = tk.Button(self, text="Rotar Derecha")
            btn_rotar_derecha.pack(side=tk.LEFT, padx=5)
            btn_rotar_izquierda = tk.Button(self, text="Rotar Izquierda")
            btn_rotar_izquierda.pack(side=tk.LEFT, padx=5)
        elif estructura_datos == "Lista Doblemente Ligada":
            boton_insertar_inicio = tk.Button(self, text="Insertar al Inicio")
            boton_insertar_inicio.pack(side=tk.LEFT, padx=5)
            boton_insertar_final = tk.Button(self, text="Insertar al Final")
            boton_insertar_final.pack(side=tk.LEFT, padx=5)
            boton_insertar_posicion = tk.Button(self, text="Insertar por Posicion")
            boton_insertar_posicion.pack(side=tk.LEFT, padx=5)
            boton_eliminar_inicio = tk.Button(self, text="Eliminar del Inicio")
            boton_eliminar_inicio.pack(side=tk.LEFT, padx=5)
            boton_eliminar_final = tk.Button(self, text="Eliminar del Final")
            boton_eliminar_final.pack(side=tk.LEFT, padx=5)
            boton_eliminar_posicion = tk.Button(self, text="Eliminar por Posicion")
            boton_eliminar_posicion.pack(side=tk.LEFT, padx=5)
            boton_buscar = tk.Button(self, text="Buscar")
            boton_buscar.pack(side=tk.LEFT, padx=5)
        elif estructura_datos == "Lista Circular Doble":
            boton_insertar_inicio = tk.Button(self, text="Insertar al Inicio")
            boton_insertar_inicio.pack(side=tk.LEFT, padx=5)
            boton_insertar_final = tk.Button(self, text="Insertar al Final")
            boton_insertar_final.pack(side=tk.LEFT, padx=5)
            boton_eliminar_inicio = tk.Button(self, text="Eliminar del Inicio")
            boton_eliminar_inicio.pack(side=tk.LEFT, padx=5)
            boton_eliminar_final = tk.Button(self, text="Eliminar del Final")
            boton_eliminar_final.pack(side=tk.LEFT, padx=5)
            btn_rotar_derecha = tk.Button(self, text="Rotar Derecha")
            btn_rotar_derecha.pack(side=tk.LEFT, padx=5)
            btn_rotar_izquierda = tk.Button(self, text="Rotar Izquierda")
            btn_rotar_izquierda.pack(side=tk.LEFT, padx=5)
            boton_buscar = tk.Button(self, text="Buscar")
            boton_buscar.pack(side=tk.LEFT, padx=5)
        elif estructura_datos == "Arbol Binario":
            boton_insertar_inicio = tk.Button(self, text="Insertar al Izquierda")
            boton_insertar_inicio.pack(side=tk.LEFT, padx=5)
            boton_insertar_final = tk.Button(self, text="Insertar al Derecha")
            boton_insertar_final.pack(side=tk.LEFT, padx=5)
            boton_eliminar = tk.Button(self, text="Eliminar")
            boton_eliminar.pack(side=tk.LEFT, padx=5)
            boton_buscar = tk.Button(self, text="Buscar")
            boton_buscar.pack(side=tk.LEFT, padx=5)
        elif estructura_datos == "Arbol de Busqueda":
            boton_insertar = tk.Button(self, text="Insertar al Derecha")
            boton_insertar.pack(side=tk.LEFT, padx=5)
            boton_eliminar = tk.Button(self, text="Eliminar")
            boton_eliminar.pack(side=tk.LEFT, padx=5)
            boton_buscar = tk.Button(self, text="Buscar")
            boton_buscar.pack(side=tk.LEFT, padx=5)
#
# if __name__ == "__main__":
#     app = VentanaOperaciones()
#     app.mainloop()
